---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: media-management-ingress-media-management-local
  namespace: media-management
spec:
  hostnames:
    - media-management.local
    - sous-chef-proxy.local
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - backendRefs:
        - name: media-management-service
          port: 3000
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/media-management
status:
  parents: []
